# Site settings
title: Gunilog
email: amazingguni@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    흔한 개발자의 자질구래한 개발 관련 블로그입니다. 
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://amazingguni.github.io/" # the base hostname & protocol for your site
twitter_username: # none
github_username:  amazingguni
disqus-shortname: amazingguni

permalink:   pretty
markdown:    redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "tables"]

highlighter: pygments



# Other options
permalink: blog/:year/:month/:title
job.title: "Beginner"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
